package com.born.analog.dao;

import com.born.analog.module.AffixBean;
import com.born.analog.module.Goods;
import com.born.analog.module.Pannel;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodsDaoConfig;
    private final DaoConfig affixBeanDaoConfig;
    private final DaoConfig pannelDaoConfig;

    private final GoodsDao goodsDao;
    private final AffixBeanDao affixBeanDao;
    private final PannelDao pannelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodsDaoConfig = daoConfigMap.get(GoodsDao.class).clone();
        goodsDaoConfig.initIdentityScope(type);

        affixBeanDaoConfig = daoConfigMap.get(AffixBeanDao.class).clone();
        affixBeanDaoConfig.initIdentityScope(type);

        pannelDaoConfig = daoConfigMap.get(PannelDao.class).clone();
        pannelDaoConfig.initIdentityScope(type);

        goodsDao = new GoodsDao(goodsDaoConfig, this);
        affixBeanDao = new AffixBeanDao(affixBeanDaoConfig, this);
        pannelDao = new PannelDao(pannelDaoConfig, this);

        registerDao(Goods.class, goodsDao);
        registerDao(AffixBean.class, affixBeanDao);
        registerDao(Pannel.class, pannelDao);
    }
    
    public void clear() {
        goodsDaoConfig.clearIdentityScope();
        affixBeanDaoConfig.clearIdentityScope();
        pannelDaoConfig.clearIdentityScope();
    }

    public GoodsDao getGoodsDao() {
        return goodsDao;
    }

    public AffixBeanDao getAffixBeanDao() {
        return affixBeanDao;
    }

    public PannelDao getPannelDao() {
        return pannelDao;
    }

}
