package com.born.analog.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.born.analog.module.Goods;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "GOODS".
*/
public class GoodsDao extends AbstractDao<Goods, Void> {

    public static final String TABLENAME = "GOODS";

    /**
     * Properties of entity Goods.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", false, "ID");
        public final static Property Type = new Property(1, int.class, "type", false, "TYPE");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Length = new Property(3, int.class, "length", false, "LENGTH");
        public final static Property Create_time = new Property(4, long.class, "create_time", false, "CREATE_TIME");
        public final static Property Creater = new Property(5, String.class, "creater", false, "CREATER");
        public final static Property Owner = new Property(6, String.class, "owner", false, "OWNER");
        public final static Property Use = new Property(7, int.class, "use", false, "USE");
        public final static Property Base_type = new Property(8, int.class, "base_type", false, "BASE_TYPE");
        public final static Property Base_name = new Property(9, String.class, "base_name", false, "BASE_NAME");
        public final static Property Base_minNumber = new Property(10, int.class, "base_minNumber", false, "BASE_MIN_NUMBER");
        public final static Property Base_maxNumber = new Property(11, int.class, "base_maxNumber", false, "BASE_MAX_NUMBER");
        public final static Property Base_number = new Property(12, int.class, "base_number", false, "BASE_NUMBER");
        public final static Property Base_space = new Property(13, int.class, "base_space", false, "BASE_SPACE");
        public final static Property Base_minSpace = new Property(14, int.class, "base_minSpace", false, "BASE_MIN_SPACE");
        public final static Property Base_maxSpace = new Property(15, int.class, "base_maxSpace", false, "BASE_MAX_SPACE");
    }


    public GoodsDao(DaoConfig config) {
        super(config);
    }
    
    public GoodsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GOODS\" (" + //
                "\"ID\" TEXT UNIQUE ," + // 0: id
                "\"TYPE\" INTEGER NOT NULL ," + // 1: type
                "\"NAME\" TEXT," + // 2: name
                "\"LENGTH\" INTEGER NOT NULL ," + // 3: length
                "\"CREATE_TIME\" INTEGER NOT NULL ," + // 4: create_time
                "\"CREATER\" TEXT," + // 5: creater
                "\"OWNER\" TEXT," + // 6: owner
                "\"USE\" INTEGER NOT NULL ," + // 7: use
                "\"BASE_TYPE\" INTEGER NOT NULL ," + // 8: base_type
                "\"BASE_NAME\" TEXT," + // 9: base_name
                "\"BASE_MIN_NUMBER\" INTEGER NOT NULL ," + // 10: base_minNumber
                "\"BASE_MAX_NUMBER\" INTEGER NOT NULL ," + // 11: base_maxNumber
                "\"BASE_NUMBER\" INTEGER NOT NULL ," + // 12: base_number
                "\"BASE_SPACE\" INTEGER NOT NULL ," + // 13: base_space
                "\"BASE_MIN_SPACE\" INTEGER NOT NULL ," + // 14: base_minSpace
                "\"BASE_MAX_SPACE\" INTEGER NOT NULL );"); // 15: base_maxSpace
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GOODS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Goods entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindLong(2, entity.getType());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
        stmt.bindLong(4, entity.getLength());
        stmt.bindLong(5, entity.getCreate_time());
 
        String creater = entity.getCreater();
        if (creater != null) {
            stmt.bindString(6, creater);
        }
 
        String owner = entity.getOwner();
        if (owner != null) {
            stmt.bindString(7, owner);
        }
        stmt.bindLong(8, entity.getUse());
        stmt.bindLong(9, entity.getBase_type());
 
        String base_name = entity.getBase_name();
        if (base_name != null) {
            stmt.bindString(10, base_name);
        }
        stmt.bindLong(11, entity.getBase_minNumber());
        stmt.bindLong(12, entity.getBase_maxNumber());
        stmt.bindLong(13, entity.getBase_number());
        stmt.bindLong(14, entity.getBase_space());
        stmt.bindLong(15, entity.getBase_minSpace());
        stmt.bindLong(16, entity.getBase_maxSpace());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Goods entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindLong(2, entity.getType());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
        stmt.bindLong(4, entity.getLength());
        stmt.bindLong(5, entity.getCreate_time());
 
        String creater = entity.getCreater();
        if (creater != null) {
            stmt.bindString(6, creater);
        }
 
        String owner = entity.getOwner();
        if (owner != null) {
            stmt.bindString(7, owner);
        }
        stmt.bindLong(8, entity.getUse());
        stmt.bindLong(9, entity.getBase_type());
 
        String base_name = entity.getBase_name();
        if (base_name != null) {
            stmt.bindString(10, base_name);
        }
        stmt.bindLong(11, entity.getBase_minNumber());
        stmt.bindLong(12, entity.getBase_maxNumber());
        stmt.bindLong(13, entity.getBase_number());
        stmt.bindLong(14, entity.getBase_space());
        stmt.bindLong(15, entity.getBase_minSpace());
        stmt.bindLong(16, entity.getBase_maxSpace());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Goods readEntity(Cursor cursor, int offset) {
        Goods entity = new Goods( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.getInt(offset + 1), // type
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.getInt(offset + 3), // length
            cursor.getLong(offset + 4), // create_time
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // creater
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // owner
            cursor.getInt(offset + 7), // use
            cursor.getInt(offset + 8), // base_type
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // base_name
            cursor.getInt(offset + 10), // base_minNumber
            cursor.getInt(offset + 11), // base_maxNumber
            cursor.getInt(offset + 12), // base_number
            cursor.getInt(offset + 13), // base_space
            cursor.getInt(offset + 14), // base_minSpace
            cursor.getInt(offset + 15) // base_maxSpace
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Goods entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setType(cursor.getInt(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLength(cursor.getInt(offset + 3));
        entity.setCreate_time(cursor.getLong(offset + 4));
        entity.setCreater(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setOwner(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setUse(cursor.getInt(offset + 7));
        entity.setBase_type(cursor.getInt(offset + 8));
        entity.setBase_name(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setBase_minNumber(cursor.getInt(offset + 10));
        entity.setBase_maxNumber(cursor.getInt(offset + 11));
        entity.setBase_number(cursor.getInt(offset + 12));
        entity.setBase_space(cursor.getInt(offset + 13));
        entity.setBase_minSpace(cursor.getInt(offset + 14));
        entity.setBase_maxSpace(cursor.getInt(offset + 15));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Goods entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Goods entity) {
        return null;
    }

    @Override
    public boolean hasKey(Goods entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
